### PR TITLE
Adds watchOS + tvOS support

### PR DESCRIPTION
**Pull request by orta**
Adds tvOS to #10

### CODE REVIEW

**Comment by itsthejb** [comment]
Thanks for this and the necessary Tweet prod 😉. I'll have a quick look into updating various things right now.

**Comment by itsthejb** [comment]
Needed some updates for Travis, so I rebased this and merged as https://github.com/itsthejb/NSURL-QueryDictionary/pull/15. Thanks!

**Comment by itsthejb** [comment]
https://github.com/itsthejb/NSURL-QueryDictionary/releases/tag/v1.2.0 and pushed to Cocoapods

**Comment by orta** [comment]
Thanks!

**Pull request closed without merging**
